# Autogenerated from /home/vwells/sources/tt-mlir/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


config.llvm_tools_dir = lit_config.substitute("/localdev/vwells/ttmlir-toolchain-x86/bin")
config.lit_tools_dir = "/localdev/vwells/ttmlir-toolchain-x86/src/llvm-project/llvm/utils/lit"
config.mlir_obj_dir = "/home/vwells/sources/tt-mlir"
config.enable_bindings_python = 1 and "ON" == "ON"
config.ttmlir_obj_root = "/home/vwells/sources/tt-mlir"
config.llvm_shlib_ext = ".so"
config.enable_stablehlo = "OFF" and "OFF" == "ON"

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "/home/vwells/sources/tt-mlir/test/lit.cfg.py")
