#!/bin/bash

# Exit on error
set -e

# Allow running only from the script directory
script_dir=$(dirname "$(realpath "$0")")
if [ "$(pwd)" != ${script_dir} ]; then
  echo "Error: must run from ${script_dir}"
  exit 1
fi

# Build
echo "==================== BUILDING TTNN STANDALONE ==================="
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++
cmake --build build -- ttnn-standalone
echo "================ FINISH BUILDING TTNN STANDALONE ================"

# Run
echo "==================== RUNNING TTNN STANDALONE ===================="
./build/ttnn-standalone
echo "================= FINISH RUNNING TTNN STANDALONE ================"
