#!/bin/bash

# Exit on error
set -e

# Allow running only from the script directory
script_dir=$(dirname "$(realpath "$0")")
if [ "$(pwd)" != ${script_dir} ]; then
  echo "Error: must run from ${script_dir}"
  exit 1
fi

# Build
echo "==================== BUILDING TTNN LOCAL ===================="
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++
$_ && cmake --build build -- ttnn-local
echo "================ FINISH BUILDING TTNN LOCAL ================="

# Run
echo "==================== RUNNING TTNN LOCAL ====================="
./build/ttnn-local
echo "================= FINISH RUNNING TTNN LOCAL ================="
