name: _build-and-test

on:
  workflow_call:
    inputs:
      sim:
        type: boolean
        default: false

jobs:
  resolve-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.tag.outputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - id: tag
        run: |
          TAG=$(cd third_party/tt-mlir && bash .github/get-docker-tag.sh)
          echo "image=ghcr.io/tenstorrent/tt-mlir/tt-mlir-ci-ubuntu-24-04:$TAG" >> $GITHUB_OUTPUT

  build-and-test:
    needs: [resolve-image]
    runs-on: [self-hosted, "${{ inputs.sim && 'compute' || 'qb' }}"]
    container:
      image: ${{ needs.resolve-image.outputs.image }}
      options: ${{ inputs.sim && '' || '--device /dev/tenstorrent -v /dev/hugepages-1G:/dev/hugepages-1G' }}
      volumes:
        - /opt/cpm-cache:/cpm-cache
      env:
        CPM_SOURCE_CACHE: /cpm-cache
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0


      # Install `tt-smi` in a venv. Adding its bin dir to $GITHUB_PATH exposes tt-smi
      # to subsequent steps.
      - name: Reset device
        if: ${{ !inputs.sim }}
        run: |
          python3 -m venv /tmp/tt-smi-venv
          /tmp/tt-smi-venv/bin/pip install tt-smi
          echo "/tmp/tt-smi-venv/bin" >> "$GITHUB_PATH"
          /tmp/tt-smi-venv/bin/tt-smi -r

      - name: Show device info
        if: ${{ !inputs.sim }}
        run: tt-smi -s --snapshot_no_tty

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: build-${{ runner.os }}-debug

      - name: Build (debug)
        shell: bash
        run: |
          source venv/activate
          ./scripts/build debug

      - name: Install torch backend
        shell: bash
        run: |
          source venv/activate
          ./scripts/install-py

      - name: Unit Test
        shell: bash
        run: |
          source venv/activate
          ./scripts/test ${{ inputs.sim && 'sim' || '' }}

      - name: Pytest Test
        shell: bash
        run: |
          source venv/activate
          pytest tests/python ${{ inputs.sim && '--sim' || '' }}
