name: on-pr-push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sim:
    uses: ./.github/workflows/_build-and-test.yml
    with:
      sim: true

  device:
    uses: ./.github/workflows/_build-and-test.yml
