// SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

// Tests for the scheduled pass fallback path: region has compute ops but NO
// d2m.linalg_root loop (e.g., the root loop was canonicalized away or the
// region was generated by DecomposeArange / DecomposeMasking).
// The scheduled pass should still insert DST accesses for the flat block.
//
// Also verifies that the unscheduled pass does NOT handle this case (it
// explicitly skips the fallback).
// RUN: ttmlir-opt --ttcore-register-device --d2m-insert-dst-register-access-scheduled --canonicalize -o %t %s
// RUN: FileCheck %s --input-file=%t

#l1_ = #ttcore.memory_space<l1>
#dst_ = #ttcore.memory_space<dst>

module {
  // -----------------------------------------------------------------------
  // Unary eltwise in a flat block (no loops at all):
  //   affine.load from CB -> tile_exp -> affine.store to CB
  //   The scheduled pass should insert acquire_dst and DST accesses.
  // -----------------------------------------------------------------------
  // CHECK-LABEL: func.func @fallback_unary_flat
  func.func @fallback_unary_flat(
      %in0: memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>,
      %out0: memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>) {
    d2m.generic {block_factors = [], grid = #ttcore.grid<1x1>, indexing_maps = [], iterator_types = [], threads = [#d2m.thread<unified>]}
        ins(%in0 : memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>)
        outs(%out0 : memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>) {
    ^unified0:
      %cb0_raw = d2m.get_cb(0) : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>>
      %cb1_raw = d2m.get_cb(1) : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>>
      %cb0 = d2m.wait %cb0_raw : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>> -> memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
      %cb1 = d2m.reserve %cb1_raw : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>> -> memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
      %v = affine.load %cb0[0, 0] : memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
      %r = "d2m.tile_exp"(%v) : (!ttcore.tile<32x32, f32>) -> !ttcore.tile<32x32, f32>
      affine.store %r, %cb1[0, 0] : memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
    }
    // CHECK: %[[DST:.*]] = d2m.acquire_dst() : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // CB -> DST load:
    // CHECK: %[[CB_VAL:.*]] = affine.load %{{.*}}[0, 0] : memref<1x1x!ttcore.tile<32x32, f32>, #l1>
    // CHECK: affine.store %[[CB_VAL]], %[[DST]][0] : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // Compute in DST:
    // CHECK: %[[DST_VAL:.*]] = affine.load %[[DST]][0] : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // CHECK: %[[EXP:.*]] = "d2m.tile_exp"(%[[DST_VAL]])
    // Result stored to DST:
    // CHECK: affine.store %[[EXP]], %[[DST]][0] : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // DST -> CB store:
    // CHECK: %[[FINAL:.*]] = affine.load %[[DST]][0] : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // CHECK: affine.store %[[FINAL]], %{{.*}}[0, 0] : memref<1x1x!ttcore.tile<32x32, f32>, #l1>
    return
  }

  // -----------------------------------------------------------------------
  // Binary eltwise in a flat block:
  //   load in0, load in1 -> tile_maximum -> store out0
  //   Two inputs with stack allocator, no loop structure.
  // -----------------------------------------------------------------------
  // CHECK-LABEL: func.func @fallback_binary_flat
  func.func @fallback_binary_flat(
      %in0: memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>,
      %in1: memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>,
      %out0: memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>) {
    d2m.generic {block_factors = [], grid = #ttcore.grid<1x1>, indexing_maps = [], iterator_types = [], threads = [#d2m.thread<unified>]}
        ins(%in0, %in1 : memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>, memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>)
        outs(%out0 : memref<1x1x1x1x!ttcore.tile<32x32, f32>, #ttcore.shard<4096x4096, 1>, #l1_>) {
    ^unified0:
      %cb0_raw = d2m.get_cb(0) : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>>
      %cb1_raw = d2m.get_cb(1) : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>>
      %cb2_raw = d2m.get_cb(2) : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>>
      %cb0 = d2m.wait %cb0_raw : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>> -> memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
      %cb1 = d2m.wait %cb1_raw : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>> -> memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
      %cb2 = d2m.reserve %cb2_raw : !d2m.cb<memref<1x1x!ttcore.tile<32x32, f32>, #l1_>> -> memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
      %a = affine.load %cb0[0, 0] : memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
      %b = affine.load %cb1[0, 0] : memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
      %r = "d2m.tile_maximum"(%a, %b) : (!ttcore.tile<32x32, f32>, !ttcore.tile<32x32, f32>) -> !ttcore.tile<32x32, f32>
      affine.store %r, %cb2[0, 0] : memref<1x1x!ttcore.tile<32x32, f32>, #l1_>
    }
    // CHECK: d2m.acquire_dst() : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // Two CB -> DST loads:
    // CHECK: affine.load %{{.*}} : memref<1x1x!ttcore.tile<32x32, f32>, #l1>
    // CHECK: affine.store %{{.*}}, %{{.*}} : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // CHECK: affine.load %{{.*}} : memref<1x1x!ttcore.tile<32x32, f32>, #l1>
    // CHECK: affine.store %{{.*}}, %{{.*}} : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // Compute reads from DST:
    // CHECK: "d2m.tile_maximum"
    // Result stored to DST then DST -> CB:
    // CHECK: affine.store %{{.*}}, %{{.*}} : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // CHECK: affine.load %{{.*}} : memref<4x!ttcore.tile<32x32, f32>, #dst>
    // CHECK: affine.store %{{.*}}, %{{.*}} : memref<1x1x!ttcore.tile<32x32, f32>, #l1>
    return
  }
}
