# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS MLIRTTDialect MLIRTTNNDialect TTMLIRTTNNUtils MLIRTTKernelDialect MLIRTTMetalDialect MLIRTTNNTransforms)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target MLIRTTDialect
add_library(MLIRTTDialect STATIC IMPORTED)

set_target_properties(MLIRTTDialect PROPERTIES
  INTERFACE_LINK_LIBRARIES "LLVM"
)

# Create imported target MLIRTTNNDialect
add_library(MLIRTTNNDialect STATIC IMPORTED)

set_target_properties(MLIRTTNNDialect PROPERTIES
  INTERFACE_LINK_LIBRARIES "TTMLIRTTNNUtils;MLIRSCFToEmitC;MLIRLinalgDialect;MLIRBufferizationDialect;MLIRMLProgramDialect;LLVM"
)

# Create imported target TTMLIRTTNNUtils
add_library(TTMLIRTTNNUtils STATIC IMPORTED)

set_target_properties(TTMLIRTTNNUtils PROPERTIES
  INTERFACE_LINK_LIBRARIES "LLVM"
)

# Create imported target MLIRTTKernelDialect
add_library(MLIRTTKernelDialect STATIC IMPORTED)

set_target_properties(MLIRTTKernelDialect PROPERTIES
  INTERFACE_LINK_LIBRARIES "MLIRTTMetalDialect;LLVM"
)

# Create imported target MLIRTTMetalDialect
add_library(MLIRTTMetalDialect STATIC IMPORTED)

set_target_properties(MLIRTTMetalDialect PROPERTIES
  INTERFACE_LINK_LIBRARIES "LLVM"
)

# Create imported target MLIRTTNNTransforms
add_library(MLIRTTNNTransforms STATIC IMPORTED)

set_target_properties(MLIRTTNNTransforms PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/vwells/sources/tt-mlir/include/ttmlir/Target/Common"
  INTERFACE_LINK_LIBRARIES "MLIRTTNNDialect;LLVM"
)

# Import target "MLIRTTDialect" for configuration ""
set_property(TARGET MLIRTTDialect APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(MLIRTTDialect PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/vwells/sources/tt-mlir/lib/libMLIRTTDialect.a"
  )

# Import target "MLIRTTNNDialect" for configuration ""
set_property(TARGET MLIRTTNNDialect APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(MLIRTTNNDialect PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/vwells/sources/tt-mlir/lib/libMLIRTTNNDialect.a"
  )

# Import target "TTMLIRTTNNUtils" for configuration ""
set_property(TARGET TTMLIRTTNNUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(TTMLIRTTNNUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/vwells/sources/tt-mlir/lib/libTTMLIRTTNNUtils.a"
  )

# Import target "MLIRTTKernelDialect" for configuration ""
set_property(TARGET MLIRTTKernelDialect APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(MLIRTTKernelDialect PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/vwells/sources/tt-mlir/lib/libMLIRTTKernelDialect.a"
  )

# Import target "MLIRTTMetalDialect" for configuration ""
set_property(TARGET MLIRTTMetalDialect APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(MLIRTTMetalDialect PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/vwells/sources/tt-mlir/lib/libMLIRTTMetalDialect.a"
  )

# Import target "MLIRTTNNTransforms" for configuration ""
set_property(TARGET MLIRTTNNTransforms APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(MLIRTTNNTransforms PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/vwells/sources/tt-mlir/lib/libMLIRTTNNTransforms.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
