// SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0
//
// POC: read program.bfbs and emit C++ switch-case bodies that gather
// input and output TensorRef pointers for ops whose .fbs fields are
// tagged with (tt_input) or (tt_output). See
// runtime/lib/ttnn/runtime.cpp for the consuming switch statements.
//
// Uses the flatbuffers C++ reflection API (no .fbs source required).

#include "flatbuffers/reflection_generated.h"
#include "flatbuffers/util.h"

#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace {

constexpr const char *kOpUnionName = "tt.target.ttnn.OpType";
constexpr const char *kCppNamespace = "tt::target::ttnn";
constexpr const char *kInputAttr = "tt_input";
constexpr const char *kOutputAttr = "tt_output";
constexpr const char *kHeader =
    "// Auto-generated by tools/op-tensor-refs-gen — do not edit.\n";

bool fieldHasAttr(const reflection::Field *field, const char *attr) {
  const auto *attrs = field->attributes();
  if (!attrs) {
    return false;
  }
  for (const auto *kv : *attrs) {
    if (kv->key() && kv->key()->str() == attr) {
      return true;
    }
  }
  return false;
}

bool fieldIsVectorOfObj(const reflection::Field *field) {
  const auto *t = field->type();
  return t->base_type() == reflection::Vector &&
         t->element() == reflection::Obj;
}

struct TaggedField {
  std::string name;
  bool isVector;
};

const reflection::Enum *findOpUnion(const reflection::Schema *schema) {
  for (const auto *e : *schema->enums()) {
    if (e->is_union() && e->name() && e->name()->str() == kOpUnionName) {
      return e;
    }
  }
  return nullptr;
}

std::vector<TaggedField> taggedFields(const reflection::Object *obj,
                                      const char *attr) {
  std::vector<TaggedField> out;
  for (const auto *f : *obj->fields()) {
    if (fieldHasAttr(f, attr)) {
      out.push_back({f->name()->str(), fieldIsVectorOfObj(f)});
    }
  }
  // Sort by FlatBuffer field offset to recover schema declaration order
  // (Object::fields() is sorted alphabetically by name).
  std::sort(out.begin(), out.end(), [obj](const TaggedField &a,
                                          const TaggedField &b) {
    auto offset = [obj](const std::string &n) {
      for (const auto *f : *obj->fields()) {
        if (f->name()->str() == n) {
          return f->offset();
        }
      }
      return uint16_t{0};
    };
    return offset(a.name) < offset(b.name);
  });
  return out;
}

std::string emitInputCase(const std::string &opName,
                          const std::vector<TaggedField> &fields) {
  std::string out;
  out += "case ::" + std::string(kCppNamespace) + "::OpType::" + opName +
         ": {\n";
  out += "  auto *op = opContext.type_as_" + opName + "();\n";
  for (const auto &f : fields) {
    if (f.isVector) {
      out += "  { auto v = utils::convertFbTensorRefsToVector(op->" + f.name +
             "());\n";
      out += "    tensorRefs.insert(tensorRefs.end(), v.begin(), v.end()); }\n";
    } else {
      out += "  if (op->" + f.name + "()) tensorRefs.push_back(op->" + f.name +
             "());\n";
    }
  }
  out += "  break;\n}\n";
  return out;
}

std::string emitOutputCase(const std::string &opName,
                           const std::vector<TaggedField> &fields) {
  if (fields.size() != 1 || fields.front().isVector) {
    std::cerr << "op-tensor-refs-gen: " << opName
              << " must have exactly one scalar TensorRef field tagged "
                 "(tt_output)\n";
    std::exit(1);
  }
  const auto &name = fields.front().name;
  return "case ::" + std::string(kCppNamespace) + "::OpType::" + opName +
         ": {\n  tensorRef = opContext.type_as_" + opName + "()->" + name +
         "();\n  break;\n}\n";
}

void writeFile(const std::string &path, const std::string &content) {
  std::ofstream f(path);
  if (!f) {
    std::cerr << "op-tensor-refs-gen: cannot open " << path << " for writing\n";
    std::exit(1);
  }
  f << content;
}

} // namespace

int main(int argc, char **argv) {
  if (argc != 4) {
    std::cerr << "usage: op-tensor-refs-gen <program.bfbs> <out_inputs.inc> "
                 "<out_outputs.inc>\n";
    return 1;
  }
  const std::string bfbsPath = argv[1];
  const std::string outInputs = argv[2];
  const std::string outOutputs = argv[3];

  std::string buf;
  if (!flatbuffers::LoadFile(bfbsPath.c_str(), /*binary=*/true, &buf)) {
    std::cerr << "op-tensor-refs-gen: cannot read " << bfbsPath << "\n";
    return 1;
  }

  const reflection::Schema *schema = reflection::GetSchema(buf.data());
  const reflection::Enum *opUnion = findOpUnion(schema);
  if (!opUnion) {
    std::cerr << "op-tensor-refs-gen: union '" << kOpUnionName
              << "' not found\n";
    return 1;
  }

  std::string inputs = kHeader;
  std::string outputs = kHeader;
  for (const auto *v : *opUnion->values()) {
    const auto *t = v->union_type();
    if (!t || t->base_type() != reflection::Obj) {
      continue; // skip the synthetic NONE entry
    }
    const auto *obj = schema->objects()->Get(t->index());
    const std::string opName = v->name()->str();

    auto ifields = taggedFields(obj, kInputAttr);
    auto ofields = taggedFields(obj, kOutputAttr);
    if (!ifields.empty()) {
      inputs += emitInputCase(opName, ifields);
    }
    if (!ofields.empty()) {
      outputs += emitOutputCase(opName, ofields);
    }
  }

  writeFile(outInputs, inputs);
  writeFile(outOutputs, outputs);
  return 0;
}
