# Autogenerated from /home/vwells/sources/tt-mlir/test/unittests/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import sys

config.llvm_src_root = ""
config.llvm_obj_root = "/localdev/vwells/ttmlir-toolchain-x86"
config.llvm_tools_dir = "/localdev/vwells/ttmlir-toolchain-x86/bin"
config.llvm_build_mode = "."
config.enable_shared = 1
config.shlibdir = ""
config.mlir_src_root = ""
config.mlir_obj_root = "/home/vwells/sources/tt-mlir"
config.mlir_tools_dir = ""

# Support substitution of the tools_dir and build_mode with user parameters.
# This is used when we can't determine the tool dir at configuration time.
try:
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_build_mode = config.llvm_build_mode % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

# Let the main config do the real work.
lit_config.load_config(config, "/home/vwells/sources/tt-mlir/test/unittests/lit.cfg.py")
