name: Update Project Date on Issue Update


on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Run workflow against a issue number (Used for testing)'
        required: false
        default: ""
        type: string

  issues:
    types: [edited, opened]
  issue_comment:
    types: [created]

env:
  project_id: PVT_kwDOA9MHEM4AjeTl
  field_id: PVTF_lADOA9MHEM4AjeTlzgiiU18
  
jobs:
  issue-last-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Run issued last updated
        uses: jmcgrathTT/tt-github-actions/.github/actions/add-last-updated@add-last-updated-workflow
        with:
          project_id: ${{ env.project_id }}
          field_id: ${{ env.field_id }}
          issue_number: ${{ github.event.issue.number || github.event.inputs.issue_number }}
          gh_token: ${{ secrets.ISSUE_TOKEN }}