name: Build on macos-latest

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: get reports
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      shell: bash
      id: rep
      run: |
        .github/scripts/get_test_runs.sh 18386355172
        cat _summary.md >> $GITHUB_STEP_SUMMARY
        cat _summary.md

    - uses: LouisBrunner/checks-action@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        sha: "0a5d19224d8d77f45b02c54955651bc79e50350e"
        name: "All Tests"
        conclusion: "neutral"
        output_text_description_file: _summary.md

    # - name: Show Test Report
    #   uses: mikepenz/action-junit-report@v5.6.2
    #   if: success() || failure()
    #   with:
    #     report_paths: report_*.xml
    #     check_name: "n150-tracy Tests"
    #     job_summary: false
    #     summary: ${{ steps.rep.outputs.summary }}

    # - name: Append to Job Summary
    #   run: |
    #     cat summary.md >> $GITHUB_STEP_SUMMARY
