# This workflow automates creation of uplift pull requests for model-explorer.
# Uplift PR is created daily to uplift the model-explorer version to the latest commit.

name: Nightly Model Explorer Uplift

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 07:00 UTC every day (staggered from tt-metal uplift)
  workflow_dispatch:  # Manual trigger

jobs:
  uplift-pr:
    runs-on: ubuntu-latest

    env:
      MODEL_EXPLORER_PATH: tools/explorer

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set env variable for today's date
        run: |
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Fetch latest SHA of model-explorer
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LATEST_MODEL_EXPLORER_VERSION=$(gh api repos/tenstorrent/model-explorer/commits/main --jq '.sha')
          echo "LATEST_MODEL_EXPLORER_VERSION=$LATEST_MODEL_EXPLORER_VERSION" >> $GITHUB_ENV

      - name: Update model-explorer reference in tools/explorer/CMakeLists.txt
        run: |
          echo "Updating model-explorer to SHA: ${{ env.LATEST_MODEL_EXPLORER_VERSION }}"
          sed -i "s/set(MODEL_EXPLORER_VERSION \".*\")/set(MODEL_EXPLORER_VERSION \"${{ env.LATEST_MODEL_EXPLORER_VERSION }}\")/" tools/explorer/CMakeLists.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: create-pr
        with:
          branch: model-explorer-uplift
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          base: main
          commit-message: "Uplift model-explorer to ${{ env.LATEST_MODEL_EXPLORER_VERSION }} ${{ env.TODAY }}"
          title: "Uplift model-explorer to ${{ env.LATEST_MODEL_EXPLORER_VERSION }} ${{ env.TODAY }}"
          body: "This PR uplifts the model-explorer version in ${{ env.MODEL_EXPLORER_PATH }} to the latest commit ${{ env.LATEST_MODEL_EXPLORER_VERSION }}"
          labels: uplift
          delete-branch: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Approve Pull Request
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_APPROVE_TOKEN }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
          gh pr review ${{ steps.create-pr.outputs.pull-request-number }} --approve

      # Note: Disabled auto-merge for now until we are more confident
      # that uplift won't break the downstream projects
      #
      # - name: Enable Pull Request Automerge
      #   if: ${{ steps.create-pr.outputs.pull-request-number }}
      #   run: gh pr merge --squash --auto "${{ steps.create-pr.outputs.pull-request-number }}"
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
