# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

"""
Ttir Dialect Plugin - GENERATED CODE

This file is automatically generated from TableGen definitions.
DO NOT EDIT MANUALLY - changes will be overwritten.

Generated from: include/ttmlir/Dialect/TTIR/IR/TTIROps.td
"""

from typing import List, Optional, Dict, Tuple
import torch

from ttmlir.ir import *
from ttmlir.dialects import func, ttir, ttcore
from ttmlir.passes import DataType
from golden import get_golden_function

from builder_prototype.dialect_plugin import DialectPlugin, tag, parse, split


class TtirPlugin(DialectPlugin):
    """
    Ttir dialect plugin - AUTO-GENERATED

    Provides TTIR operations with plugin architecture.
    Generated from TableGen operation definitions.
    """

    def register_ops(self, builder) -> None:
        """Register TTIR operations with the builder."""
        # Operations are automatically discovered via decorators
        pass

    def create_tensor_encoding(
        self, builder, tensor_type: RankedTensorType, memory_space: str = "system"
    ) -> Attribute:
        """Create TTIR tensor encoding attribute."""
        # TTIR-specific tensor encoding
        grid = ttcore.ir.GridAttr.get(builder.context, [0, 0], [0, 0])

        memory_space_enum = ttcore.ir.MemorySpace.System
        if memory_space == "device":
            memory_space_enum = ttcore.ir.MemorySpace.DeviceDRAM
        elif memory_space == "l1":
            memory_space_enum = ttcore.ir.MemorySpace.DeviceL1

        memory_attr = ttcore.ir.MemorySpaceAttr.get(builder.context, memory_space_enum)

        memory_config = ttcore.ir.MemoryConfigEncodingAttr.get(
            builder.context,
            memory_attr,
            ttcore.ir.TensorMemoryLayoutAttr.get(
                builder.context, ttcore.ir.TensorMemoryLayout.Interleaved
            ),
            ttcore.ir.BufferTypeAttr.get(builder.context, ttcore.ir.BufferType.DRAM),
            None,
        )

        return memory_config

    # ----- Generated Operations -----

    @tag(ttir.SigmoidOp)
    def sigmoid(
        self,
        builder,
        in0: Operand,
        output_type: Optional[torch.dtype] = None,
        loc: Optional[str] = None,
        unit_attrs: Optional[List[str]] = None,
    ) -> OpResult:
        """
        Eltwise sigmoid.

        Args:
            builder: Builder instance
            in0: Input operand
            output_type: Optional output dtype (defaults to input dtype)
            loc: Optional location string for debugging
            unit_attrs: Optional unit attributes to add to operation

        Returns:
            Operation result
        """
        op_class = ttir.SigmoidOp

        # Determine output type
        if output_type is None:
            mlir_output_type = builder.get_type(in0)
        else:
            mlir_output_type = builder._get_type_from_torch_dtype(output_type)

        # Get golden tensor and compute output
        input0 = builder._get_golden_tensor(in0)
        op_golden_function = get_golden_function(op_class)
        golden_output = op_golden_function(input0, mlir_output_type)
        result = RankedTensorType.get(golden_output.shape, mlir_output_type)

        # Create location
        if loc is None:
            loc = Location.unknown(builder.context)
        else:
            loc = Location.name(loc)

        # Create MLIR operation
        op = op_class(result, in0, loc=loc)
        op_result = op.result

        # Add unit attributes if specified
        if unit_attrs is not None:
            for attr_name in unit_attrs:
                op.operation.attributes[attr_name] = UnitAttr.get(builder.context)

        # Store golden tensor
        builder._set_golden_tensor(op_result, golden_output)

        return op_result

    @parse(ttir.SigmoidOp)
    def sigmoid_parser(
        self,
        builder,
        old_op: ttir.SigmoidOp,
        global_dict: Dict[Operand, Operand],
    ) -> Tuple[Operation, Dict[OpResult, OpResult]]:
        """Parse sigmoid operation from existing MLIR."""
        op_class = ttir.SigmoidOp
        in0 = global_dict[old_op.input]
        result = old_op.result.type

        # Create new operation
        new_op = op_class(result, in0, loc=old_op.location)
        new_op_result = new_op.result

        # Compute golden output
        input0 = builder._get_golden_tensor(in0)
        op_golden_function = get_golden_function(op_class)
        golden_output = op_golden_function(input0, result.element_type)
        builder._set_golden_tensor(new_op_result, golden_output)

        # Map old result to new result
        op_map_dictionary = {}
        op_map_dictionary[old_op.result] = new_op_result
        return new_op, op_map_dictionary

    @split(ttir.SigmoidOp)
    def sigmoid_split(
        self,
        builder,
        old_op: ttir.SigmoidOp,
    ) -> Tuple[Module, "Builder"]:
        """Split sigmoid operation into separate module."""
        op_class = ttir.SigmoidOp

        old_ctx = old_op.context
        old_loc = Location.unknown(old_ctx)
        with old_ctx, old_loc:
            sigmoid_module = Module.create()

            # Create new builder for split module
            from builder_prototype.builder import Builder

            sigmoid_builder = Builder(
                old_ctx,
                old_loc,
                mesh_name=builder._mesh_name,
                mesh_dict=builder._mesh_dict,
            )
            # Register same dialects as parent
            for dialect_name, plugin in builder._plugins.items():
                sigmoid_builder.register_dialect(dialect_name, plugin)

            op_input_types = [old_op.input.type]

            with InsertionPoint(sigmoid_module.body):
                ordered_inputs = []
                ordered_outputs = []

                @func.func(*op_input_types, name="sigmoid_module")
                def decorated_func(*inputs):
                    in0 = inputs[0]
                    result = old_op.result.type

                    new_op = op_class(result, in0, loc=old_op.location)
                    new_op_result = new_op.result

                    input0 = builder._get_golden_tensor(old_op.input)
                    old_op_result = builder._get_golden_tensor(old_op.result)
                    sigmoid_builder._set_golden_tensor(new_op_result, old_op_result)
                    sigmoid_builder._set_golden_tensor(in0, input0)
                    ordered_inputs.append(in0)
                    ordered_outputs.append(new_op_result)

                    return new_op

                new_func_op = decorated_func.func_op
                sigmoid_builder._func_ops_generated[new_func_op] = [
                    ordered_inputs,
                    ordered_outputs,
                ]

        return sigmoid_module, sigmoid_builder

    @tag(ttir.ReluOp)
    def relu(
        self,
        builder,
        in0: Operand,
        output_type: Optional[torch.dtype] = None,
        loc: Optional[str] = None,
        unit_attrs: Optional[List[str]] = None,
    ) -> OpResult:
        """
        Eltwise ReLU.

        Args:
            builder: Builder instance
            in0: Input operand
            output_type: Optional output dtype (defaults to input dtype)
            loc: Optional location string for debugging
            unit_attrs: Optional unit attributes to add to operation

        Returns:
            Operation result
        """
        op_class = ttir.ReluOp

        # Determine output type
        if output_type is None:
            mlir_output_type = builder.get_type(in0)
        else:
            mlir_output_type = builder._get_type_from_torch_dtype(output_type)

        # Get golden tensor and compute output
        input0 = builder._get_golden_tensor(in0)
        op_golden_function = get_golden_function(op_class)
        golden_output = op_golden_function(input0, mlir_output_type)
        result = RankedTensorType.get(golden_output.shape, mlir_output_type)

        # Create location
        if loc is None:
            loc = Location.unknown(builder.context)
        else:
            loc = Location.name(loc)

        # Create MLIR operation
        op = op_class(result, in0, loc=loc)
        op_result = op.result

        # Add unit attributes if specified
        if unit_attrs is not None:
            for attr_name in unit_attrs:
                op.operation.attributes[attr_name] = UnitAttr.get(builder.context)

        # Store golden tensor
        builder._set_golden_tensor(op_result, golden_output)

        return op_result

    @parse(ttir.ReluOp)
    def relu_parser(
        self,
        builder,
        old_op: ttir.ReluOp,
        global_dict: Dict[Operand, Operand],
    ) -> Tuple[Operation, Dict[OpResult, OpResult]]:
        """Parse relu operation from existing MLIR."""
        op_class = ttir.ReluOp
        in0 = global_dict[old_op.input]
        result = old_op.result.type

        # Create new operation
        new_op = op_class(result, in0, loc=old_op.location)
        new_op_result = new_op.result

        # Compute golden output
        input0 = builder._get_golden_tensor(in0)
        op_golden_function = get_golden_function(op_class)
        golden_output = op_golden_function(input0, result.element_type)
        builder._set_golden_tensor(new_op_result, golden_output)

        # Map old result to new result
        op_map_dictionary = {}
        op_map_dictionary[old_op.result] = new_op_result
        return new_op, op_map_dictionary

    @split(ttir.ReluOp)
    def relu_split(
        self,
        builder,
        old_op: ttir.ReluOp,
    ) -> Tuple[Module, "Builder"]:
        """Split relu operation into separate module."""
        op_class = ttir.ReluOp

        old_ctx = old_op.context
        old_loc = Location.unknown(old_ctx)
        with old_ctx, old_loc:
            relu_module = Module.create()

            # Create new builder for split module
            from builder_prototype.builder import Builder

            relu_builder = Builder(
                old_ctx,
                old_loc,
                mesh_name=builder._mesh_name,
                mesh_dict=builder._mesh_dict,
            )
            # Register same dialects as parent
            for dialect_name, plugin in builder._plugins.items():
                relu_builder.register_dialect(dialect_name, plugin)

            op_input_types = [old_op.input.type]

            with InsertionPoint(relu_module.body):
                ordered_inputs = []
                ordered_outputs = []

                @func.func(*op_input_types, name="relu_module")
                def decorated_func(*inputs):
                    in0 = inputs[0]
                    result = old_op.result.type

                    new_op = op_class(result, in0, loc=old_op.location)
                    new_op_result = new_op.result

                    input0 = builder._get_golden_tensor(old_op.input)
                    old_op_result = builder._get_golden_tensor(old_op.result)
                    relu_builder._set_golden_tensor(new_op_result, old_op_result)
                    relu_builder._set_golden_tensor(in0, input0)
                    ordered_inputs.append(in0)
                    ordered_outputs.append(new_op_result)

                    return new_op

                new_func_op = decorated_func.func_op
                relu_builder._func_ops_generated[new_func_op] = [
                    ordered_inputs,
                    ordered_outputs,
                ]

        return relu_module, relu_builder

    @tag(ttir.CosOp)
    def cos(
        self,
        builder,
        in0: Operand,
        output_type: Optional[torch.dtype] = None,
        loc: Optional[str] = None,
        unit_attrs: Optional[List[str]] = None,
    ) -> OpResult:
        """
        Eltwise cosine.

        Args:
            builder: Builder instance
            in0: Input operand
            output_type: Optional output dtype (defaults to input dtype)
            loc: Optional location string for debugging
            unit_attrs: Optional unit attributes to add to operation

        Returns:
            Operation result
        """
        op_class = ttir.CosOp

        # Determine output type
        if output_type is None:
            mlir_output_type = builder.get_type(in0)
        else:
            mlir_output_type = builder._get_type_from_torch_dtype(output_type)

        # Get golden tensor and compute output
        input0 = builder._get_golden_tensor(in0)
        op_golden_function = get_golden_function(op_class)
        golden_output = op_golden_function(input0, mlir_output_type)
        result = RankedTensorType.get(golden_output.shape, mlir_output_type)

        # Create location
        if loc is None:
            loc = Location.unknown(builder.context)
        else:
            loc = Location.name(loc)

        # Create MLIR operation
        op = op_class(result, in0, loc=loc)
        op_result = op.result

        # Add unit attributes if specified
        if unit_attrs is not None:
            for attr_name in unit_attrs:
                op.operation.attributes[attr_name] = UnitAttr.get(builder.context)

        # Store golden tensor
        builder._set_golden_tensor(op_result, golden_output)

        return op_result

    @parse(ttir.CosOp)
    def cos_parser(
        self,
        builder,
        old_op: ttir.CosOp,
        global_dict: Dict[Operand, Operand],
    ) -> Tuple[Operation, Dict[OpResult, OpResult]]:
        """Parse cos operation from existing MLIR."""
        op_class = ttir.CosOp
        in0 = global_dict[old_op.input]
        result = old_op.result.type

        # Create new operation
        new_op = op_class(result, in0, loc=old_op.location)
        new_op_result = new_op.result

        # Compute golden output
        input0 = builder._get_golden_tensor(in0)
        op_golden_function = get_golden_function(op_class)
        golden_output = op_golden_function(input0, result.element_type)
        builder._set_golden_tensor(new_op_result, golden_output)

        # Map old result to new result
        op_map_dictionary = {}
        op_map_dictionary[old_op.result] = new_op_result
        return new_op, op_map_dictionary

    @split(ttir.CosOp)
    def cos_split(
        self,
        builder,
        old_op: ttir.CosOp,
    ) -> Tuple[Module, "Builder"]:
        """Split cos operation into separate module."""
        op_class = ttir.CosOp

        old_ctx = old_op.context
        old_loc = Location.unknown(old_ctx)
        with old_ctx, old_loc:
            cos_module = Module.create()

            # Create new builder for split module
            from builder_prototype.builder import Builder

            cos_builder = Builder(
                old_ctx,
                old_loc,
                mesh_name=builder._mesh_name,
                mesh_dict=builder._mesh_dict,
            )
            # Register same dialects as parent
            for dialect_name, plugin in builder._plugins.items():
                cos_builder.register_dialect(dialect_name, plugin)

            op_input_types = [old_op.input.type]

            with InsertionPoint(cos_module.body):
                ordered_inputs = []
                ordered_outputs = []

                @func.func(*op_input_types, name="cos_module")
                def decorated_func(*inputs):
                    in0 = inputs[0]
                    result = old_op.result.type

                    new_op = op_class(result, in0, loc=old_op.location)
                    new_op_result = new_op.result

                    input0 = builder._get_golden_tensor(old_op.input)
                    old_op_result = builder._get_golden_tensor(old_op.result)
                    cos_builder._set_golden_tensor(new_op_result, old_op_result)
                    cos_builder._set_golden_tensor(in0, input0)
                    ordered_inputs.append(in0)
                    ordered_outputs.append(new_op_result)

                    return new_op

                new_func_op = decorated_func.func_op
                cos_builder._func_ops_generated[new_func_op] = [
                    ordered_inputs,
                    ordered_outputs,
                ]

        return cos_module, cos_builder

    @tag(ttir.AbsOp)
    def abs(
        self,
        builder,
        in0: Operand,
        output_type: Optional[torch.dtype] = None,
        loc: Optional[str] = None,
        unit_attrs: Optional[List[str]] = None,
    ) -> OpResult:
        """
        Elementwise absolute value operation.

        Args:
            builder: Builder instance
            in0: Input operand
            output_type: Optional output dtype (defaults to input dtype)
            loc: Optional location string for debugging
            unit_attrs: Optional unit attributes to add to operation

        Returns:
            Operation result
        """
        op_class = ttir.AbsOp

        # Determine output type
        if output_type is None:
            mlir_output_type = builder.get_type(in0)
        else:
            mlir_output_type = builder._get_type_from_torch_dtype(output_type)

        # Get golden tensor and compute output
        input0 = builder._get_golden_tensor(in0)
        op_golden_function = get_golden_function(op_class)
        golden_output = op_golden_function(input0, mlir_output_type)
        result = RankedTensorType.get(golden_output.shape, mlir_output_type)

        # Create location
        if loc is None:
            loc = Location.unknown(builder.context)
        else:
            loc = Location.name(loc)

        # Create MLIR operation
        op = op_class(result, in0, loc=loc)
        op_result = op.result

        # Add unit attributes if specified
        if unit_attrs is not None:
            for attr_name in unit_attrs:
                op.operation.attributes[attr_name] = UnitAttr.get(builder.context)

        # Store golden tensor
        builder._set_golden_tensor(op_result, golden_output)

        return op_result

    @parse(ttir.AbsOp)
    def abs_parser(
        self,
        builder,
        old_op: ttir.AbsOp,
        global_dict: Dict[Operand, Operand],
    ) -> Tuple[Operation, Dict[OpResult, OpResult]]:
        """Parse abs operation from existing MLIR."""
        op_class = ttir.AbsOp
        in0 = global_dict[old_op.input]
        result = old_op.result.type

        # Create new operation
        new_op = op_class(result, in0, loc=old_op.location)
        new_op_result = new_op.result

        # Compute golden output
        input0 = builder._get_golden_tensor(in0)
        op_golden_function = get_golden_function(op_class)
        golden_output = op_golden_function(input0, result.element_type)
        builder._set_golden_tensor(new_op_result, golden_output)

        # Map old result to new result
        op_map_dictionary = {}
        op_map_dictionary[old_op.result] = new_op_result
        return new_op, op_map_dictionary

    @split(ttir.AbsOp)
    def abs_split(
        self,
        builder,
        old_op: ttir.AbsOp,
    ) -> Tuple[Module, "Builder"]:
        """Split abs operation into separate module."""
        op_class = ttir.AbsOp

        old_ctx = old_op.context
        old_loc = Location.unknown(old_ctx)
        with old_ctx, old_loc:
            abs_module = Module.create()

            # Create new builder for split module
            from builder_prototype.builder import Builder

            abs_builder = Builder(
                old_ctx,
                old_loc,
                mesh_name=builder._mesh_name,
                mesh_dict=builder._mesh_dict,
            )
            # Register same dialects as parent
            for dialect_name, plugin in builder._plugins.items():
                abs_builder.register_dialect(dialect_name, plugin)

            op_input_types = [old_op.input.type]

            with InsertionPoint(abs_module.body):
                ordered_inputs = []
                ordered_outputs = []

                @func.func(*op_input_types, name="abs_module")
                def decorated_func(*inputs):
                    in0 = inputs[0]
                    result = old_op.result.type

                    new_op = op_class(result, in0, loc=old_op.location)
                    new_op_result = new_op.result

                    input0 = builder._get_golden_tensor(old_op.input)
                    old_op_result = builder._get_golden_tensor(old_op.result)
                    abs_builder._set_golden_tensor(new_op_result, old_op_result)
                    abs_builder._set_golden_tensor(in0, input0)
                    ordered_inputs.append(in0)
                    ordered_outputs.append(new_op_result)

                    return new_op

                new_func_op = decorated_func.func_op
                abs_builder._func_ops_generated[new_func_op] = [
                    ordered_inputs,
                    ordered_outputs,
                ]

        return abs_module, abs_builder
